### ISSUE TITLE
OSC-dependent handlers stop working, then never work again

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#291] opened 2022-01-20 20:14 UTC
No specific repro steps, but have seen this twice now.
This is against Pegasus (production) server

SYMPTOM: Getting IMAGE renderings, semantic segmentations results are not returned for ANY graphics at all, including those that had always returned semantic segmentation results in the past no longer does. Restarting all IMAGE containers makes it work again, until it happens again.

It may be that #290 helps trigger this bug, but unclear. After last restart of all IMAGE containers, I basically just played with multiple photographs from the image.a11y.mcgill.ca homepage 

Semantic segmentation looks like it is being run since the log shows 
`atp-semantic-segmentation        | [2022-01-20 19:09:15 +0000] [9] [DEBUG] POST /preprocessor`, but there are no other errors when this occurs. This is why we need #289.

In fact, it looks like only the text rendering is being returned. Note the tts an semseg handler timeouts in the log:

atp-first-categoriser            | [2022-01-20 20:11:28 +0000] [9] [DEBUG] POST /preprocessor
atp-autour-preprocessor          | 172.27.0.3 - - [20/Jan/2022 20:11:28] "POST /preprocessor HTTP/1.1" 204 -
atp-autour-preprocessor          | INFO:werkzeug:172.27.0.3 - - [20/Jan/2022 20:11:28] "POST /preprocessor HTTP/1.1" 204 -
atp-second-categoriser           | [2022-01-20 20:11:28 +0000] [9] [DEBUG] POST /preprocessor
atp-object-detection             | [2022-01-20 20:11:28 +0000] [31] [DEBUG] POST /preprocessor
atp-object-detection             | YOLOv5 🚀 v6.0-0-g956be8e torch 1.9.1+cu102 CPU
atp-object-detection             | 
atp-object-detection             | Fusing layers... 
atp-object-detection             | Model Summary: 476 layers, 87730285 parameters, 0 gradients
atp-semantic-segmentation        | [2022-01-20 20:11:30 +0000] [9] [DEBUG] POST /preprocessor
atp-object-grouping              | [2022-01-20 20:11:31 +0000] [9] [DEBUG] POST /preprocessor
atp-object-sorting               | [2022-01-20 20:11:31 +0000] [9] [DEBUG] POST /preprocessor
atp-espnet-tts                   | [2022-01-20 20:11:31 +0000] [8] [DEBUG] POST /service/tts/segments
atp-espnet-tts                   | 2022-01-20 20:11:31,489 Done performing TTS
atp-espnet-tts                   | 2022-01-20 20:11:31,490 Encoded
atp-espnet-tts                   | [2022-01-20 20:11:31 +0000] [8] [DEBUG] POST /service/tts/segments
atp-espnet-tts                   | 2022-01-20 20:11:31,493 Done performing TTS
atp-espnet-tts                   | 2022-01-20 20:11:31,493 Encoded
atp-generic-tts-handler          | Forming OSC...
atp-semseg-handler               | Forming OSC...
atp-generic-tts-handler          | Timeout
atp-semseg-handler               | Timeout
atp-orchestrator                 | Valid response generated.

**Comment by JRegimbal** [comment] 2022-01-20 21:12
After rebuilding all of the images from scratch, I can't reproduce this issue. The image OOMs, but then the handlers haven't timed out after. Sometimes the generic-tts-handler cannot generate a rendering due to the lack of data returned by object detection. This behavior does seem similar to #223 which also resulted in all handlers depending on supercollider timing out. Such an issue is still technically possible, but unlikely since semantic segmentation length is capped and object detection has not (in my experience) returned enough objects to lead to a timeout.

**Comment by JRegimbal** [comment] 2022-01-26 16:58
Closing for now since a likely explanation is that this was already fixed and even then would be mitigated by additional changes to the photo handlers.

**Closed by JRegimbal** 2022-01-26 16:58 UTC
Labels: bug
