### ISSUE TITLE
Implement additional measures/interpretations to raw chart data

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#429] opened 2022-04-22 04:05 UTC
@florian-grond has suggested that for sonifying charts, having information such as maxima and minima already calculated would be useful, and would probably help people building other handlers as well. There is some debate about whether this should be an additional preprocessor that ingests chart data and adds to it, or a more dynamic service/library called by the handlers. Ideas include things like:

- labeling each data point with its local maximum / minimum window, e.g., how many points before and after are lower/higher than it. (and/or some other max/min metric)
- - things specific to charts like candlestick charts, if we need to identify common patterns ourselves.
- @florian-grond other examples?

**Comment by Cybernide** [comment] 2022-04-22 13:26
For your first bullet, it seems as if we would need to implement a way of navigating from "window" to "window" - should I make this a UX/UI issue?

**Comment by jeffbl** [comment] 2022-04-25 18:48
@Cybernide that is between you and the people designing the handler(s) for this, which means @florian-grond / @JRegimbal. Design work for this is in #431 .

**Comment by jeffbl** [comment] 2022-08-04 02:44
After discussion today, first set of new columns will be these four:
1. number of contiguous points to right that are higher
2. number of contiguous points to the left that are higher
3. number of contiguous points to the right that are lower
4. number of contiguous points to the left that are lower

We verified with @florian-grond that this should be sufficient for the initial sonfications he wants to try.

For intial PR, brute force is ok, but there are easy optimizations based on previous point that should make this much faster than the worst case O(n^2), which could bog down on charts with many points. For example, if the point to the left of the one currently under consideration had 15 points lower to the left, and the current point is higher than the one to the left, re-counting is not necessary since we know that there are 15+1=16 points lower to the left.

Once this is implemented and checked in (this is the first functionality requiring an actual charts preprocessor to be implemented), doing further tweaks/columns should be pretty trivial, barring CPU load for the actual processing.

Discussed adding some sort of moving average column as well, which might be useful in tandem with the data for finding local max/min values for some of Florian's use cases.

**Comment by jeffbl** [comment] 2022-08-26 19:34
@jaydeepsingh25 This should be closed by #475, correct? Any further columns to be implemented should be logged as new work items.

**Comment by jaydeepsingh25** [comment] 2022-08-26 20:23
yes, the issue is closed by #475

**Closed by jaydeepsingh25** 2022-08-26 20:23 UTC
