### ISSUE TITLE
Design mechanism and format for additional chart data measures

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#431] opened 2022-04-25 18:48 UTC
This is not implementation, just a design and example JSON format for [this item](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/429) so that @florian-grond can begin planning handler support while the design is actually implemented in the next sprint.

**Comment by jeffbl** [comment] 2022-08-26 19:35
@jaydeepsingh25 also closed by #465, correct?

**Comment by jaydeepsingh25** [comment] 2022-08-26 20:22
The issue is closed by PR #475

**Closed by jaydeepsingh25** 2022-08-26 20:22 UTC
